export const BASE_TOKEN_INFO: ITokenListItem = {
    name: "",
    logo: "",
    profitPersend: 0,
    profitValue: 0,
    valueUsd: 0,
    value: 0,
    mcap: "",
    tokenPrice: "",
    five_min: 0,
    one_hour: 0,
    six_hour: 0,
    address: "",
    type: "",
    pair: "",
    volume: "",
    initialSol: 0,
    initialUsd: 0,
    holder: 0,
}